apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      containers:
      - name: the-project-container
        image: dockergauge/the-project:v5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: MESSAGE
          value: "Hello from Kubernetes environment"
---
apiVersion: v1
kind: Service
metadata:
  name: the-project-svc # Note the service name here
spec:
  type: ClusterIP
  selector:
    app: the-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80